<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit960f3af6149a2152aa3b8fb6ffb29880
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit960f3af6149a2152aa3b8fb6ffb29880::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit960f3af6149a2152aa3b8fb6ffb29880::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
